-- TPC-H/TPC-R Forecasting Revenue Change (Q6)
-- Postgres Query Definition
/*Returns the revenue generated by all lineitem shipments in a specific year 
with a quantity less than a specified amount and a discount 
within a species amount +-.01.*/

CREATE INDEX idx_shipdate_discount_quant_quantity on lineitem (l_shipdate)
    AND L_DISCOUNT BETWEEN [DISCOUNT] - 0.01 AND [DISCOUNT] + 0.01
    AND L_QUANTITY < [QUANTITY];
SELECT
    SUM(L_EXTENDEDPRICE * L_DISCOUNT) AS REVENUE
FROM
    LINEITEM
WHERE
    L_SHIPDATE >= '[DATE]'::DATE
    AND L_SHIPDATE < '[DATE]'::DATE + '1 Year'::INTERVAL
    AND L_DISCOUNT BETWEEN [DISCOUNT] - 0.01 AND [DISCOUNT] + 0.01
    AND L_QUANTITY < [QUANTITY];
DROP INDEX idx_shipdate_discount_quant_quantity;
