-- TPC-H/TPC-R National Market Share (Q8)
-- Postgres Query Definition
/*Returns fraction of the total revenue for a specific type of product in a
specific region was generated by suppliers in a specific nation for the years 
1995 to 1996.*/

SELECT
    o_year,
    sum(
        CASE WHEN nation = '[NATION]'
        THEN volume
        ELSE 0
        end) / sum(volume) AS mkt_share
FROM (
    SELECT
        extract(year FROM o_orderdate) AS o_year,
        l_extendedprice * (1 - l_discount) AS volume,
        n2.n_name AS nation
    FROM
        part,
        supplier,
        lineitem,
        orders,
        customer,
        nation n1,
        nation n2,
        region
    WHERE
        p_partkey = l_partkey
        and s_suppkey = l_suppkey
        AND l_orderkey = o_orderkey
        AND o_custkey = c_custkey
        AND c_nationkey = n1.n_nationkey
        AND n1.n_regionkey = r_regionkey
        AND r_name = '[REGION]'
        AND s_nationkey = n2.n_nationkey
        AND o_orderdate BETWEEN date '1995-01-01' AND date '1996-12-31'
        AND p_type = '[TYPE]'
    ) AS all_nations
    group BY
        o_year
    order BY
        o_year;
